Repository valory-xyz/trader, pull requests merged in 2023-11, with the labels that each got.

#121 Store redeeming progress
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#116 Remove redeeming limit
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#124 Add missing balance check
  .github/workflows/common_checks.yaml
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: fix

#126 Update the synchronized database correctly on network error
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/rounds.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#125 Fix redeeming
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/rounds.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#131 Fix contracts' message propagation
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#130 Update Kelly formula
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#134 Fix zero division
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#136 Check max bet amount
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/decision_request.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#142 Check agents' balances
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/trader_abci/composition.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/behaviours.py
  packages/valory/skills/tx_settlement_multiplexer_abci/fsm_specification.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/models.py
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#141 Reduce event filtering window in case of failure
  .gitleaksignore
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/composition.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/behaviours.py
  packages/valory/skills/tx_settlement_multiplexer_abci/fsm_specification.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/models.py
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#140 Bump open-autonomy@0.13.4
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/agent_registry/contract.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#151 Avoid to repeatedly check the same markets when redeeming
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/redeem.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#152 Fix db update after the first redeeming period
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/redeem.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#153 Fix #152
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/redeem.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#154 Bump `open-autonomy` and `open-aea` frameworks, and `tomte`
  .github/workflows/common_checks.yaml
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/agent_registry/contract.yaml
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech/contract.yaml
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  scripts/check_dependencies.py
  tox.ini
Labels: bump

#155 Persist the status of the clean operation for the redeeming round
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#156 Persist the dynamic changes to the batch size
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#159 Do not proceed if gateway is unreachable
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix
