Repository valory-xyz/trader, pull requests merged in 2023-10, with the labels that each got.

#97 Log the name of the selected tool
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: refactor

#99 Feat/store tools
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: enhancement

#105 Fix redeem amount
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#108 Refactor profitability decision
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: refactor

#107 Utilize wxDAI to perform requests
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.py
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_request.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#110 Fix tools' loading logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#111 Fix the mech tools' recover logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#112 Fix suggested amount
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/decision_request.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#114 Do not expect a strict response format from the mech
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#115 Handle invalid responses
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix
