Repository valory-xyz/trader, pull requests merged in 2023-09, with the labels that each got.

#67 Fix uniqueness of positions to redeem
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#69 Fix typo
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/trader_abci/behaviours.py
  packages/valory/skills/trader_abci/skill.yaml
Labels: fix

#70 Lock dependencies
  poetry.lock
Labels: chore

#71 Fix contract error reporting
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#74 Add slippage
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#73 Fix exception handling
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  pyproject.toml
  tox.ini
Labels: fix

#72 Make the strategy more sensible
  README.md
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_request.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/decision_request.py
  packages/valory/skills/market_manager_abci/bets.py
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  pyproject.toml
  tox.ini
Labels: enhancement

#76 Fix RPC timeouts
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#80 Bump `open-autonomy` and `open-aea` frameworks
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#81 Fix release workflow
  .github/workflows/release.yaml
Labels: fix

#83 fix: optionally call `claimWinnings`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: fix

#95 Fix strategy
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/redeem.py
  packages/valory/skills/decision_maker_abci/states/tool_selection.py
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#96 Fix checkout action
  .github/workflows/release.yaml
Labels: fix
