Repository valory-xyz/trader, pull requests merged in 2023-08, with the labels that each got.

#37 Fix the swap logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#38 Make some fields optional
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/bets.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#39 Bump `open-aea` and `open-autonomy ` frameworks
  .gitignore
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  scripts/run_service.sh
  tox.ini
Labels: bump

#42 Hide secret inputs
  scripts/run_service.sh
Labels: enhancement

#45 Implement a script to get trades
  scripts/trades.py
Labels: enhancement

#46 Stop previous containers
  scripts/run_service.sh
Labels: enhancement

#47 Bump `open-autonomy` to `v0.10.11`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#48 Bump open-autonomy to `v0.10.11.post1`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/erc20/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#43 1-run deployment with fresh keys
  scripts/run_service.sh
Labels: enhancement

#49 Add support for re-running the service via the script
  scripts/run_service.sh
Labels: enhancement

#61 Loop on the same state until Mech delivers
  .gitleaksignore
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: refactor

#62 Fix indefinite loop
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#63 Improve `decision_maker_abci` package description
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: documentation

#59 Implement autonomous claiming
  .gitleaksignore
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/__init__.py
  packages/valory/contracts/conditional_tokens/build/ConditionalTokens.json
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/__init__.py
  packages/valory/contracts/realitio/build/Realitio.json
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/contracts/realitio_proxy/__init__.py
  packages/valory/contracts/realitio_proxy/build/Realitio.json
  packages/valory/contracts/realitio_proxy/contract.py
  packages/valory/contracts/realitio_proxy/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_request.py
  packages/valory/skills/decision_maker_abci/behaviours/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/round_behaviour.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/final_states.py
  packages/valory/skills/decision_maker_abci/states/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/states/redeem.py
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/composition.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/fsm_specification.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#65 Fix redeeming
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/conditional_tokens/contract.py
  packages/valory/contracts/conditional_tokens/contract.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#66 Finish the redeeming logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/realitio/contract.py
  packages/valory/contracts/realitio/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/redeem_info.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/graph_tooling/queries/network.py
  packages/valory/skills/market_manager_abci/graph_tooling/queries/omen.py
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  tox.ini
Labels: fix
