Repository valory-xyz/trader, pull requests merged in 2024-12, with the labels that each got.

#365 Fix formatting error and problematic property and increase the chances of meeting the KPIs
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/handlers.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/decision_receive.py
  packages/valory/skills/decision_maker_abci/tests/states/test_decision_receive.py
  packages/valory/skills/decision_maker_abci/tests/states/test_order_subscription.py
  packages/valory/skills/decision_maker_abci/tests/test_payloads.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#367 Update the bets so that we map all the investments per vote
  .github/workflows/merge_rules.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/market_manager_abci/bets.py
Labels: enhancement

#368 Release `v0.21.1`
  .github/workflows/release.yaml
Labels: release

#370 Fix utilized chain id
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/order_subscription.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/staking_abci/behaviours.py
  packages/valory/skills/staking_abci/models.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/behaviours.py
  packages/valory/skills/tx_settlement_multiplexer_abci/models.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#358 Hotfix/staking kpi reachability
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/behaviours.py
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/bets.py
  packages/valory/skills/market_manager_abci/rounds.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/behaviours.py
  packages/valory/skills/staking_abci/models.py
  packages/valory/skills/staking_abci/payloads.py
  packages/valory/skills/staking_abci/rounds.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/staking_abci/tests/test_payloads.py
  packages/valory/skills/staking_abci/tests/test_rounds.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#371 Release `v0.21.2`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/behaviours.py
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/bets.py
  packages/valory/skills/market_manager_abci/rounds.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/behaviours.py
  packages/valory/skills/staking_abci/models.py
  packages/valory/skills/staking_abci/payloads.py
  packages/valory/skills/staking_abci/rounds.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/staking_abci/tests/test_payloads.py
  packages/valory/skills/staking_abci/tests/test_rounds.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  tox.ini
Labels: release

#373 Fix ignored `irrelevant_tools` configuration
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: fix

#372 Implement a mechanism for detecting and recovering quickly from unreliable tools
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/check_benchmarking.py
  packages/valory/skills/decision_maker_abci/states/claim_subscription.py
  packages/valory/skills/decision_maker_abci/states/decision_receive.py
  packages/valory/skills/decision_maker_abci/states/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/tests/states/test_base.py
  packages/valory/skills/decision_maker_abci/tests/states/test_check_benchmarking.py
  packages/valory/skills/decision_maker_abci/tests/states/test_decision_receive.py
  packages/valory/skills/decision_maker_abci/tests/states/test_handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/tests/test_payloads.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: enhancement

#374 Release `v0.21.3`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/check_benchmarking.py
  packages/valory/skills/decision_maker_abci/states/claim_subscription.py
  packages/valory/skills/decision_maker_abci/states/decision_receive.py
  packages/valory/skills/decision_maker_abci/states/handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/tests/states/test_base.py
  packages/valory/skills/decision_maker_abci/tests/states/test_check_benchmarking.py
  packages/valory/skills/decision_maker_abci/tests/states/test_decision_receive.py
  packages/valory/skills/decision_maker_abci/tests/states/test_handle_failed_tx.py
  packages/valory/skills/decision_maker_abci/tests/test_payloads.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: release
