Repository valory-xyz/trader, pull requests merged in 2024-07, with the labels that each got.

#288 Add support for updating the policy in benchmarking mode
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#291 Fix benchmarking policy
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#292 Make the randomness configurable for the benchmarking
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#294 Fix the randomness while in benchmarking mode
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#295 Handles exhausted "The Graph" API key
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/graph_tooling/requests.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/rounds.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#298 [v0.16.5]: Reschedule changes for the next release
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/blacklisting.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/tool_selection.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: chore

#296 [v0.17.0]: Update the policy's logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/reedem.py
  packages/valory/skills/decision_maker_abci/behaviours/tool_selection.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/utils/scaling.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#302 Test the handlers
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/check_stop_trading_abci/tests/test_handlers.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/tests/test_handlers.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/market_manager_abci/tests/test_handlers.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/staking_abci/tests/test_handers.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/trader_abci/tests/__init__.py
  packages/valory/skills/trader_abci/tests/tests_handlers.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/tests/__init__.py
  packages/valory/skills/tx_settlement_multiplexer_abci/tests/test_handlers.py
Labels: test

#300 [v0.18.0]: Feat/dynamic kellyfraction
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/customs/kelly_criterion_no_conf/component.yaml
  packages/valory/customs/kelly_criterion_no_conf/kelly_criterion_no_conf.py
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/tests/behaviours/test_base.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#306 Release `v0.18.0`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/customs/kelly_criterion_no_conf/component.yaml
  packages/valory/customs/kelly_criterion_no_conf/kelly_criterion_no_conf.py
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/storage_manager.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/tests/behaviours/test_base.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: release
