Repository valory-xyz/trader, pull requests merged in 2025-02, with the labels that each got.

#392 Temporary fix for the multi-bets logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: fix

#383 Bumps frameworks to latest
  .gitignore
  Makefile
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/agent_registry/__init__.py
  packages/valory/contracts/agent_registry/build/AgentRegistry.json
  packages/valory/contracts/agent_registry/contract.py
  packages/valory/contracts/agent_registry/contract.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech_activity/contract.yaml
  packages/valory/contracts/relayer/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/contracts/staking_token/contract.yaml
  packages/valory/contracts/transfer_nft_condition/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/claim_subscription.py
  packages/valory/skills/decision_maker_abci/states/handle_failed_tx.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/rounds.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/rounds.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#397 Bump the frameworks to the latest versions
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech_activity/contract.yaml
  packages/valory/contracts/relayer/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/contracts/staking_token/contract.yaml
  packages/valory/contracts/transfer_nft_condition/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#399 Bump the frameworks to the latest versions
  .github/workflows/merge_rules.yaml
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech_activity/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/contracts/staking_token/contract.yaml
  packages/valory/contracts/transfer_nft_condition/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: bump

#400 Release `v0.24.2`
  .github/workflows/common_checks.yaml
  .github/workflows/merge_rules.yaml
  .gitignore
  Makefile
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/contracts/market_maker/contract.yaml
  packages/valory/contracts/mech_activity/contract.yaml
  packages/valory/contracts/service_staking_token/contract.yaml
  packages/valory/contracts/staking_token/contract.yaml
  packages/valory/contracts/transfer_nft_condition/contract.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/behaviours/decision_receive.py
  packages/valory/skills/decision_maker_abci/behaviours/sampling.py
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/market_manager_abci/behaviours.py
  packages/valory/skills/market_manager_abci/bets.py
  packages/valory/skills/market_manager_abci/models.py
  packages/valory/skills/market_manager_abci/skill.yaml
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/models.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
  pyproject.toml
  tox.ini
Labels: release

#402 Handle too early request for healthcheck
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/handlers.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
Labels: enhancement

#403 Release `v0.25.0`
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/handlers.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: release

#404 Skip buy amount calculation on first failure
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/behaviours/bet_placement.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/bet_placement.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: enhancement
