Repository valory-xyz/trader, pull requests merged in 2025-09, with the labels that each got.

#532 fix(1): weighted accuracy weights
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/decision_maker_abci/policy.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/tests/test_policy.py
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  tox.ini
Labels: fix

#541 Remove the obsolete NVM subscription logic
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/behaviours/base.py
  packages/valory/skills/decision_maker_abci/behaviours/claim_subscription.py
  packages/valory/skills/decision_maker_abci/behaviours/order_subscription.py
  packages/valory/skills/decision_maker_abci/behaviours/round_behaviour.py
  packages/valory/skills/decision_maker_abci/fsm_specification.yaml
  packages/valory/skills/decision_maker_abci/models.py
  packages/valory/skills/decision_maker_abci/payloads.py
  packages/valory/skills/decision_maker_abci/rounds.py
  packages/valory/skills/decision_maker_abci/rounds_info.py
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/states/base.py
  packages/valory/skills/decision_maker_abci/states/check_benchmarking.py
  packages/valory/skills/decision_maker_abci/states/claim_subscription.py
  packages/valory/skills/decision_maker_abci/states/final_states.py
  packages/valory/skills/decision_maker_abci/states/order_subscription.py
  packages/valory/skills/decision_maker_abci/tests/states/test_check_benchmarking.py
  packages/valory/skills/decision_maker_abci/tests/states/test_claim_subscription.py
  packages/valory/skills/decision_maker_abci/tests/states/test_final_states.py
  packages/valory/skills/decision_maker_abci/tests/states/test_order_subscription.py
  packages/valory/skills/decision_maker_abci/tests/test_payloads.py
  packages/valory/skills/decision_maker_abci/tests/test_rounds.py
  packages/valory/skills/decision_maker_abci/utils/nevermined.py
  packages/valory/skills/staking_abci/skill.yaml
  packages/valory/skills/trader_abci/composition.py
  packages/valory/skills/trader_abci/fsm_specification.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/models.py
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  tox.ini
Labels: refactor

#582 Add support for the step-in functionality
  packages/packages.json
  packages/valory/agents/trader/aea-config.yaml
  packages/valory/services/trader/service.yaml
  packages/valory/services/trader_pearl/service.yaml
  packages/valory/skills/check_stop_trading_abci/skill.yaml
  packages/valory/skills/decision_maker_abci/skill.yaml
  packages/valory/skills/trader_abci/skill.yaml
  packages/valory/skills/tx_settlement_multiplexer_abci/skill.yaml
  poetry.lock
Labels: enhancement
